groups/urls.py
from django.urls import path

from . import views

app_name = "groups"

urlpatterns = [
    path('list', views.GroupList.as_view(), name='list'),
    path('create', views.GroupCreateView.as_view(), name='create'),
    path('edit/<str:uuid>', views.GroupEditView.as_view(), name='edit'),
    path('delete/<str:uuid>', views.GroupDeleteView.as_view(), name='delete'),
    path('generate_groups', views.generate_groups, name='generate'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('accounts.urls')),

    path('', index, name="index")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
import random
import datetime as dt

from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.db import models

from core.models import BaseModel
from students.models import Student
from teachers.models import Teacher
from core.utils import generate_uuid


# Create your models here.
class Classroom(models.Model):
    name = models.CharField(max_length=32)
    floor = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

    def __str__(self):
        return f"{self.name}, {self.floor}"


class Group(BaseModel):
    MAX_STUDENTS = 16
    group_number = models.IntegerField()
    course = models.CharField(max_length=128, default="unnamed course")
    curator = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True)
    students = models.ManyToManyField(Student, related_name='groups')
    headman = models.OneToOneField(Student, on_delete=models.SET_NULL, null=True)
    classroom = models.ManyToManyField(Classroom, related_name='cls_groups')
    starting_date = models.DateTimeField()
    uuid = models.UUIDField(default=generate_uuid, unique=True)

    def clean(self):
        if self.id:
            if self.headman not in self.students.all():
                raise ValidationError('Head of the Group not Group\'s student')

    def __str__(self):
        return f"{self.course}, {self.starting_date.date()}"

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    @staticmethod
    def generate_group(students_count=MAX_STUDENTS):
        COURSE_NAME = [
            "Cyber Security Course",
            "Python Basic Course",
            "Python Advanced Course",
            "Learn All Programming Languages in 10 seconds",
            "'Hello, World!' Crash Course",
        ]
        group_number = random.randint(1000, 1999)
        course = random.choice(COURSE_NAME)
        curator = random.choice(Teacher.objects.all())
        students = []
        students_query = Student.objects.all()
        for _ in range(students_count):
            students.append(random.choice(students_query))
        starting_date = dt.date.today()
        headman = Student.objects.filter(groups__isnull=True).order_by('?').first()

        gr = Group(
            group_number=group_number,
            course=course,
            curator=curator,
            headman=headman,
            starting_date=starting_date,
        )
        gr.save()
        gr.students.add(*students)
        gr.save()

groups/forms.py
from django import forms

from .models import Group


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        exclude = ['uuid', ]

groups/views.py
from django.shortcuts import reverse
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.views.generic import UpdateView, ListView, CreateView, DeleteView
from django.urls import reverse_lazy

from core.views import LoginRequiredBaseMixin
from .models import Group
from .forms import GroupCreateForm
from core.utils import parse_count


# Create your views here.
class GroupList(ListView):
    model = Group
    context_object_name = 'groups'
    template_name = 'groups/list.html'
    RELATED = ['headman', 'curator']
    paginate_by = 5

    def get_object(self):
        obj = super().get_object()
        for param in self.RELATED:
            obj.select_related(param)
        return obj


class GroupEditView(LoginRequiredBaseMixin, UpdateView):
    model = Group
    form_class = GroupCreateForm
    template_name = 'groups/edit.html'
    success_url = reverse_lazy('groups:list')
    context_object_name = 'group'
    pk_url_kwarg = 'uuid'

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uuid=uuid)


class GroupCreateView(LoginRequiredBaseMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    template_name = 'groups/create.html'
    success_url = reverse_lazy('groups:list')
    context_object_name = 'group'
    pk_url_kwarg = 'uuid'


class GroupDeleteView(LoginRequiredBaseMixin, DeleteView):
    model = Group
    pk_url_kwarg = 'uuid'

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uuid=uuid)


def generate_groups(request):
    try:
        count = parse_count(request)
    except Exception as ex:
        return HttpResponseBadRequest(str(ex))
    for _ in range(count):
        Group.generate_group()
    return HttpResponseRedirect(reverse('groups:list'))

groups/templates/groups/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Group-Create
    {% endblock %}
    {% block header %}Group Creation Page{% endblock %}
    {% block link_to_app %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'groups:create' %}">Create group</a>
    </li>
    {% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input type="submit" value="Create">
        </form>
    {% endblock %}

groups/templates/groups/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Group-Edit
    {% endblock %}
    {% block header %}Edit Group{% endblock %}
    {% block link_to_app %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'groups:create' %}">Create group</a>
    </li>
    {% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input type="submit" value="Edit">
            <input class="btn btn-light" formaction="{% url 'groups:delete' group.uuid %}" type="submit" value="Delete">
        </form>
    {% endblock %}

groups/templates/groups/list.html
{% extends 'base.html' %}
    {% block title %}
        Groups list        
    {% endblock %}
    {% block header %}Groups list{% endblock %}
    {% block link_to_app %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'groups:create' %}">Create group</a>
    </li>
    {% endblock %}
    {% block body %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Group number</th>
                    <th scope="col">Course</th>
                    <th scope="col">Curator</th>
                    <th scope="col">Students</th>
                    <th scope="col">Starting date</th>
                    <th scope="col">Edit</th>
                </tr>
            </thead>
            {% for group in groups %}
            <tbody>
                <tr>
                    <td><a href="{% url 'groups:edit' group.uuid %}">{{ group.group_number }} - (edit)</a></td>
                    <td>{{ group.course }}</td>
                    <td>{{ group.curator }}</td>
                    <td>{% if group.headman %}
                            Head of the Group - {{ group.headman.first_name }} {{ group.headman.last_name }}
                            <br>
                        {% endif %}
                        {% for student in group.students.all %}                        
                        {{ student.first_name }} {{student.last_name}}<br>
                        {% endfor %}
                    </td>
                    <td>{{ group.starting_date.date }}</td>
                    <td><a class="btn btn-info" href="{% url 'groups:edit' group.uuid %}">Edit</a></td>
                </tr>
            </tbody>           
            {% endfor %}
        </table>
        {% include 'includes/pagination.html' %}
    {% endblock %}