lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('accounts.urls')),

    path('', index, name="index")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from . import views

app_name = "students"

urlpatterns = [
    path('', views.hello, name='hello'),
    path('password', views.get_random, name="password"),
    path('generate_students', views.generate_students),
    path('list', views.StudentList.as_view(), name="list"),
    path('create', views.StudentCreateView.as_view(), name="create"),
    path('edit/<str:uuid>', views.StudentEditView.as_view(), name="edit"),
    path('delete/<str:uuid>', views.StudentDeleteView.as_view(), name="delete"),
]

teachers/urls.py
from django.urls import path

from . import views

app_name = "teachers"

urlpatterns = [
    path('list', views.TeacherList.as_view(), name='list'),
    path('create', views.TeacherCreateView.as_view(), name="create"),
    path('edit/<str:uuid>', views.TeacherEditView.as_view(), name="edit"),
    path('delete/<str:uuid>', views.TeacherDeleteView.as_view(), name="delete")
]

teachers/models.py
from django.db import models # noqa

from core.models import Person


# Create your models here.
class Teacher(Person):
    pass

teachers/forms.py
from django import forms

from .models import Teacher


class TeacherCreateForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = (
            "first_name",
            "last_name",
            "birthdate",
        )

teachers/views.py
from django.views.generic import UpdateView, ListView, CreateView, DeleteView
from django.urls import reverse_lazy

from core.views import LoginRequiredBaseMixin
from .models import Teacher
from .forms import TeacherCreateForm


# Create your views here.
class TeacherList(ListView):
    model = Teacher
    context_object_name = 'teachers'
    template_name = 'teachers/list.html'
    pk_url_kwarg = 'uuid'
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset()
        request = self.request
        params = [
            'first_name',
            'last_name',
        ]
        for param in params:
            value = request.GET.get(param)
            if value:
                qs = qs.filter(**{param: value})
        return qs


class TeacherEditView(LoginRequiredBaseMixin, UpdateView):
    login_url = 'accounts:login'
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'teachers/edit.html'
    success_url = reverse_lazy('teachers:list')
    context_object_name = 'teacher'
    pk_url_kwarg = 'uuid'

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uuid=uuid)


class TeacherCreateView(LoginRequiredBaseMixin, CreateView):
    login_url = 'accounts:login'
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'tachers/create.html'
    success_url = reverse_lazy('tachers:list')
    context_object_name = 'teacher'
    pk_url_kwarg = 'uuid'


class TeacherDeleteView(LoginRequiredBaseMixin, DeleteView):
    login_url = 'accounts:login'
    model = Teacher
    pk_url_kwarg = 'uuid'

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uuid=uuid)

teachers/templates/teachers/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Teacher-Create
    {% endblock %}
    {% block header %}Teacher Creation Page{% endblock %}
    {% block link_to_app %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'teachers:create' %}">Create Teacher</a>
    </li>
    {% endblock %}
    {% block body%}
   
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Create">
        </form>
    {% endblock %}

teachers/templates/teachers/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Teacher-Edit
    {% endblock %}
    {% block header %}Edit Teacher{% endblock %}
    {% block link_to_app %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'teachers:create' %}">Create Teacher</a>
    </li>
    {% endblock %}
    {% block body%}
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Edit">
            <input class="btn btn-light" formaction="{% url 'teachers:delete' teacher.uuid %}" type="submit" value="Delete">
        </form>
    {% endblock %}

teachers/templates/teachers/list.html
{% extends 'base.html' %}
    {% block title %}
        Teachers list
    {% endblock %}
    {% block header %} Teachers list{% endblock %}
    {% block link_to_app %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'teachers:create' %}">Create Teacher</a>
    </li>
    {% endblock %}
    {% block body%}
        <form action="{% url 'students:list' %}">
            <label>First name</label>
            <input type="text" name="first_name">

            <label>Last name</label>
            <input type="text" name="last_name">

            <input type="submit" value="Search">
        </form>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Birthdate</th>
                <th scope="col">Edit</th>
              </tr>
            </thead>
        {% for teacher in teachers %}
            <tbody>
                <tr>
                    <td>{{ teacher.first_name }}</td>
                    <td>{{ teacher.last_name }}</td>
                    <td>{{ teacher.birthdate.date }}</td>
                    <td><a class="btn btn-info" href="{% url 'teachers:edit' teacher.uuid %}">Edit</a></td>
                </tr>
            </tbody>
        {% endfor %}
        </table>
        {% include 'includes/pagination.html' %}
        
    {% endblock %}