accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('register', views.AccountCreateView.as_view(), name='register'),
    path('login', views.AccountLoginView.as_view(), name='login'),
    path('logout', views.AccountLogoutView.as_view(), name='logout'),
    path('profile', views.AccountUpdateView.as_view(), name='profile'),
    path('password', views.AccountPasswordView.as_view(), name='password')
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('accounts.urls')),

    path('', index, name="index")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import os
import sys

from io import BytesIO
from PIL import Image

from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models  # noqa

from lms.settings import BASE_DIR


# Create your models here.


class UserAction(models.Model):
    class USER_ACTION(models.IntegerChoices):
        LOGIN = 0, "Login"
        LOGOUT = 1, "Logout"
        CHANGE_PASSWORD = 2, "Change Password"
        CHANGE_PROFILE = 3, "Change Profile"
        CHANGE_PROFILE_IMAGE = 4, "Change Profile Image"

    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    write_date = models.DateTimeField(auto_now_add=True)
    action = models.PositiveSmallIntegerField(choices=USER_ACTION.choices)
    info = models.CharField(max_length=128, null=True)

    @classmethod
    def record_action(cls, request, action, info=None):
        user = request.user
        if info is None:
            info = f"{ user.username } performed an action: { action }"
        usac = cls(
            user=user,
            action=action,
            info=info
        )
        usac.save()

    @classmethod
    def record_image_action(cls, request, old, new):
        info = f'{request.user.username} changed picture from "{old}" to "{new}"'
        cls.record_action(
            request=request,
            action=UserAction.USER_ACTION.CHANGE_PROFILE_IMAGE,
            info=info
        )

    def __str__(self):
        return f'{self.info}'


class Profile(models.Model):
    PROFILE_IMAGES_DIRECTORY = os.path.join(BASE_DIR, 'media/profile_pics/')
    MAX_SIZE_PX = 300
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    image = models.ImageField(null=True, default='default.jpeg', upload_to='profile_pics/')
    interests = models.CharField(max_length=128, null=True)

    def save(self, *args, **kwargs):
        self.image = self.resize_profile_image(self.image, self.MAX_SIZE_PX)
        saver = super().save(*args, **kwargs)
        return saver

    def __str__(self):
        return f'{self.user.username}\'s profile'

    @staticmethod
    def resize_profile_image(image, max_size):
        with Image.open(image) as img:
            output = BytesIO()
            if (img.size[0] or img.size[1]) > max_size:
                img.thumbnail((max_size, max_size))
                img.save(output, format='jpeg')
                return InMemoryUploadedFile(
                    (pic := output), # noqa
                    'ImageField',
                    image.name,
                    'image/jpeg',
                    sys.getsizeof(pic),
                    None
                )
            return image

accounts/forms.py
from accounts.models import Profile
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import ModelForm


class AccountCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]


class AccountUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = [
            'username',
            'first_name',
            'last_name',
        ]


class AccountPasswordForm(PasswordChangeForm):
    pass


class AccountProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'interests']

accounts/views.py
from django.shortcuts import HttpResponseRedirect, render # noqa
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib import messages

from django.views.generic import CreateView
from django.views.generic.edit import ProcessFormView
from django.urls import reverse_lazy, reverse

from .forms import AccountCreateForm, AccountPasswordForm, AccountProfileForm, AccountUpdateForm
from .models import Profile, UserAction

# Create your views here.


class AccountCreateView(CreateView):
    model = User
    template_name = 'accounts/registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('index')


class AccountLoginView(LoginView):
    template_name = 'accounts/login.html'

    def get_redirect_url(self):
        return reverse('index')

    def form_valid(self, form):
        valid = super().form_valid(form)
        UserAction.record_action(request=self.request, action=UserAction.USER_ACTION.LOGIN)
        if valid:
            messages.success(self.request, 'Logged in Successfully.')
            try:
                profile = self.request.user.profile
            except Exception:
                profile = Profile.objects.create(user=self.request.user)
                profile.save()
        return valid


class AccountLogoutView(LogoutView):
    template_name = 'accounts/logout.html'

    # def get_redirect_url(self):
    #     if self.request.GET.get('next'):
    #         return self.request.GET
    #     return reverse('index')

    def form_valid(self, form):
        UserAction.record_action(request=self.request, action=UserAction.USER_ACTION.LOGOUT)
        if (valid := super().form_valid(form)): # noqa
            messages.warning(self.request, 'Account Logged out.')
        return valid


# class AccountUpdateView(UpdateView):
#     model = User
#     template_name = 'accounts/profile.html'
#     form_class = AccountUpdateForm
#     success_url = reverse_lazy('index')

#     def get_object(self, queryset=None):
#         return self.request.user

#     def form_valid(self, form):
#         UserAction.record_action(request=self.request, action=UserAction.USER_ACTION.CHANGE_PROFILE)
#         if (valid := super().form_valid(form)): # noqa
#             messages.success(self.request, 'Account Changed Successfully.')
#         return valid


class AccountPasswordView(PasswordChangeView):
    template_name = 'accounts/password.html'
    form_class = AccountPasswordForm
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        UserAction.record_action(request=self.request, action=UserAction.USER_ACTION.CHANGE_PASSWORD)
        if (valid := super().form_valid(form)): # noqa
            messages.success(self.request, 'Password Changed Successfully.')
        return valid


class AccountUpdateView(ProcessFormView):
    def get(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(instance=user)
        profile_form = AccountProfileForm(instance=profile)
        return render(
            request=request,
            template_name='accounts/profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form,
            }
        )

    def post(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(
            instance=user,
            data=request.POST
        )
        profile_form = AccountProfileForm(
            instance=profile,
            data=request.POST,
            files=request.FILES,
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            pr = Profile.objects.get(user=user)
            old_image = pr.image.name
            profile_form.save()
            if old_image != profile_form.cleaned_data['image'].name:
                UserAction.record_image_action(request=request, old=old_image, new=request.FILES.get('image').name)
            return HttpResponseRedirect(reverse('accounts:profile'))

        return render(
            request=request,
            template_name='accounts/profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form
            }
        )

    def form_valid(self, form):
        UserAction.record_action(request=self.request, action=UserAction.USER_ACTION.CHANGE_PROFILE)
        if (valid := super().form_valid(form)): # noqa
            messages.success(self.request, 'Account Changed Successfully.')
        return valid

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Log in user
    {% endblock %}
    {% block header %}Log in Page{% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Log in">
        </form>
    {% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Log out
    {% endblock %}
    {% block header %}Logged out{% endblock %}
    {% block body %}
        <a class="btn btn-light" href="{% url 'accounts:login' %}">Log in</a>
        <a class="btn btn-light" href="{% url 'index' %}">Home</a>
    {% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Password change
    {% endblock %}
    {% block header %}Change password{% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Save">
        </form>
    {% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Profile
    {% endblock %}
    {% block header %}Profile edit page{% endblock %}
    {% block body %}
        <form method="POST" enctype="multipart/form-data">
            <img class="img-thumbnail p-1 m-2" width="200px" height="200px" src="{{ user.profile.image.url }}" alt="profile_pic">
            
            {% csrf_token %}
            {{ profile_form|crispy }}
            {{ user_form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Save">
            <input class="btn btn-light" formaction="{% url 'accounts:password' %}" type="submit" value="Change Password">
        </form>
    {% endblock %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Register
    {% endblock %}
    {% block header %}Register New Account{% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Create">
        </form>
    {% endblock %}