accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('register', views.AccountCreateView.as_view(), name='register'),
    path('login', views.AccountLoginView.as_view(), name='login'),
    path('logout', views.AccountLogoutView.as_view(), name='logout'),
    path('profile', views.AccountUpdateView.as_view(), name='profile'),
    path('password', views.AccountPasswordView.as_view(), name='password')
]

groups/urls.py
from django.urls import path

from . import views

app_name = "groups"

urlpatterns = [
    path('list', views.GroupList.as_view(), name='list'),
    path('create', views.GroupCreateView.as_view(), name='create'),
    path('edit/<str:uuid>', views.GroupEditView.as_view(), name='edit'),
    path('delete/<str:uuid>', views.GroupDeleteView.as_view(), name='delete'),
    path('generate_groups', views.generate_groups, name='generate'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('accounts.urls')),

    path('', index, name="index")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path

from . import views

app_name = "students"

urlpatterns = [
    path('', views.hello, name='hello'),
    path('password', views.get_random, name="password"),
    path('generate_students', views.generate_students),
    path('list', views.StudentList.as_view(), name="list"),
    path('create', views.StudentCreateView.as_view(), name="create"),
    path('edit/<str:uuid>', views.StudentEditView.as_view(), name="edit"),
    path('delete/<str:uuid>', views.StudentDeleteView.as_view(), name="delete"),
]

teachers/urls.py
from django.urls import path

from . import views

app_name = "teachers"

urlpatterns = [
    path('list', views.TeacherList.as_view(), name='list'),
    path('create', views.TeacherCreateView.as_view(), name="create"),
    path('edit/<str:uuid>', views.TeacherEditView.as_view(), name="edit"),
    path('delete/<str:uuid>', views.TeacherDeleteView.as_view(), name="delete")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/styles/styles.css' %}">
</head>
<body>  
      <div>
        <div id="logo_line">
        <img id="lms_logo" src="{% static 'images/lms_pic.jpeg' %}">
        </div>
        <div>       
          <ul class="nav justify-content-end">
              {% block link_to_app %}
              {% endblock %} 
              <li class="nav-item">
              <a class="nav-link active" href="{% url 'index' %}">Index</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'teachers:list' %}">Teachers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'students:list' %}">Students</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link p-1 m-1" href="{% url 'accounts:profile' %}">Logged in as <b>{{ user.username }}</b>  <img class="rounded-circle" width="25px" height="25px" src="{{ user.profile.image.url }}"></a>
                  
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>
              {% endif%}
          </ul>
        </div>
    </div>
    <hr>
    <div id="headers" class="shadow-sm p-3 mb-5 bg-white text-center rounded">
      <h1>{% block header %}{% endblock %}</h1>
      {% include 'includes/messages_handler.html' %}
    </div>
    {% block body %}
    {% endblock %}
</body>

templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block header %}Index Page{% endblock %}
{% block body %}
    <div class="jumbotron jumbotron-fluid" style="margin-right: 20px;; margin-left: 20px;">
        <div class="container" >
            <h1 class="display-4" style="color: blue">This is an Index Page</h1>
            <p class="lead">This page created for testing and learning purpose only.</p>
            <p class="lead"> At the top-right corner you can see links. Just press them. Ok?</p>
        </div>
    </div>
{% endblock %}